In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('../Data/2025_full_data.csv')

C:\Users\MSI\AppData\Local\Temp\ipykernel_9236\437088706.py:1: DtypeWarning: Columns (21,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/2025_full_data.csv')

In [17]:
df.head()

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,end_dt_ther,dur_ther,dur_cod_ther,caseid_outc,outc_cod_outc,caseid_rpsr,rpsr_cod_rpsr,caseid_indi,indi_drug_seq_indi,indi_pt_indi
0,100294532,10029453,2,F,NaN,20250319,20140322,20250326,EXP,NaN,...,"nan, nan","nan, nan","nan, nan",10029453,OT,NaN,NaN,"10029453, 10029453, 10029453, 10029453, 100294...","1, 2, 3, 4, 5, 7","Breast cancer metastatic, Breast cancer metast..."
1,100496573,10049657,3,F,20111201.0,20140324,20140401,20250307,EXP,NaN,...,"nan, 201202.0, nan, nan","nan, 14892.0, nan, nan","nan, HR, nan, nan",10049657,OT,NaN,NaN,"10049657, 10049657, 10049657","1, 5, 6","Glycogen storage disease type II, Premedicatio..."
2,100546853,10054685,3,F,20130901.0,20140414,20140402,20250227,PER,NaN,...,"20121015.0, 20121015.0, 20121015.0, 20121015.0...","nan, nan, 1.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, DAY, nan, nan, nan, nan, nan, nan, nan",NaN,NaN,NaN,NaN,10054685,1,Maternal exposure during breast feeding
3,1005762122,10057621,22,F,20140204.0,20250106,20140404,20250110,EXP,NaN,...,"nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",10057621,HO,NaN,NaN,"10057621, 10057621, 10057621, 10057621, 100576...","1, 39, 40, 41, 42, 43, 44, 45, 46, 47","Asthma, Product used for unknown indication, P..."
4,100683138,10068313,8,F,20140101.0,20250129,20140409,20250203,PER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10068313, 10068313, 10068313","1, 3, 5","Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [18]:
df.columns

Index(['primaryid', 'caseid', 'caseversion', 'i_f_code', 'event_dt', 'mfr_dt',
       'init_fda_dt', 'fda_dt', 'rept_cod', 'auth_num', 'mfr_num', 'mfr_sndr',
       'lit_ref', 'age', 'age_cod', 'age_grp', 'sex', 'e_sub', 'wt', 'wt_cod',
       'rept_dt', 'to_mfr', 'occp_cod', 'reporter_country', 'occr_country',
       'caseid_drug', 'drug_seq_drug', 'role_cod_drug', 'drugname_drug',
       'prod_ai_drug', 'val_vbm_drug', 'route_drug', 'dose_vbm_drug',
       'cum_dose_chr_drug', 'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug',
       'lot_num_drug', 'exp_dt_drug', 'nda_num_drug', 'dose_amt_drug',
       'dose_unit_drug', 'dose_form_drug', 'dose_freq_drug', 'caseid_reac',
       'pt_reac', 'drug_rec_act_reac', 'caseid_ther', 'dsg_drug_seq_ther',
       'start_dt_ther', 'end_dt_ther', 'dur_ther', 'dur_cod_ther',
       'caseid_outc', 'outc_cod_outc', 'caseid_rpsr', 'rpsr_cod_rpsr',
       'caseid_indi', 'indi_drug_seq_indi', 'indi_pt_indi'],
      dtype='object')

In [19]:
df.isna().sum()/len(df) * 100

primaryid              0.000000
caseid                 0.000000
caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
mfr_dt                 0.000000
init_fda_dt            0.000000
fda_dt                 0.000000
rept_cod               0.000000
auth_num              90.759371
mfr_num                3.367350
mfr_sndr               0.000000
lit_ref               90.856252
age                   39.685763
age_cod               39.681807
age_grp               63.983483
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
wt_cod                83.082444
rept_dt                0.000000
to_mfr                96.810832
occp_cod              13.877018
reporter_country       0.000124
occr_country           4.925116
caseid_drug            0.000000
drug_seq_drug          0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
lot_num_drug          26.961923
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
caseid_reac            0.000000
pt_reac                0.000000
drug_rec_act_reac     37.487233
caseid_ther           51.015800
dsg_drug_seq_ther     51.015800
start_dt_ther         53.154050
end_dt_ther           72.696242
dur_ther              75.461716
dur_cod_ther          75.462025
caseid_outc           43.137753
outc_cod_outc         43.137753
caseid_rpsr           97.316940
rpsr_cod_rpsr         97.316940
caseid_indi            6.974894
indi_drug_seq_indi     6.974894
indi_pt_indi           6.974894
dtype: float64

In [20]:
cols_to_drop = [
    'mfr_dt', 'init_fda_dt', 'fda_dt', 
    'auth_num',
    'lit_ref',
    'age_grp',
    'rpsr_cod_rpsr',
    'primaryid',
    'caseid', 'caseid_drug', 'caseid_reac', 'caseid_ther', 'caseid_outc', 'caseid_rpsr', 'caseid_indi',
    'mfr_num',
    'to_mfr',
    'reporter_country',
    'drug_seq_drug','dsg_drug_seq_ther','indi_drug_seq_indi',
    'lot_num_drug',
    'start_dt_ther',
    'end_dt_ther',
    'dur_ther'
]

df = df.drop(columns=cols_to_drop)

In [21]:
df.head()

,caseversion,i_f_code,event_dt,rept_cod,mfr_sndr,age,age_cod,sex,e_sub,wt,...,nda_num_drug,dose_amt_drug,dose_unit_drug,dose_form_drug,dose_freq_drug,pt_reac,drug_rec_act_reac,dur_cod_ther,outc_cod_outc,indi_pt_indi
0,2,F,NaN,EXP,NOVARTIS,53.0,YR,F,Y,NaN,...,"20726.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","Asthenia, Breast cancer metastatic, Palmar-pla...","nan, nan, nan, nan, nan, nan","nan, nan",OT,"Breast cancer metastatic, Breast cancer metast..."
1,3,F,20111201.0,EXP,SANOFI AVENTIS,12.0,YR,M,Y,30.0,...,"125141.0, 125141.0, 125141.0, 125141.0, nan, nan","20.0, nan, 10.0, 20.0, nan, nan","MG/KG, nan, MG/KG, MG/KG, nan, nan","Powder for solution for infusion, Powder for s...","QOW, nan, QOW, QOW, nan, nan","Hepatic fibrosis, Red blood cell sedimentation...","nan, nan, nan, nan, nan, nan, nan, nan, nan, nan","nan, HR, nan, nan",OT,"Glycogen storage disease type II, Premedicatio..."
2,3,F,20130901.0,PER,AMGEN,1.0,YR,M,Y,NaN,...,"103795.0, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Solution for injection, nan, nan, nan, nan, na...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Increased tendency to bruise, Exposure via bre...","nan, nan","nan, nan, DAY, nan, nan, nan, nan, nan, nan, nan",NaN,Maternal exposure during breast feeding
3,22,F,20140204.0,EXP,ROCHE,57.0,YR,M,Y,53.0,...,"103976.0, 103976.0, 103976.0, 103976.0, 103976...","225.0, 225.0, 375.0, 300.0, 225.0, nan, 375.0,...","MG, MG, MG, MG, MG, nan, MG, MG, MG, MG, MG, M...","INJECTION, SOLUTION, INJECTION, SOLUTION, INJE...","nan, nan, nan, nan, nan, nan, Q3W, nan, nan, n...","Dizziness, Dysphonia, Rhinitis allergic, Photo...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",HO,"Asthma, Product used for unknown indication, P..."
4,8,F,20140101.0,PER,PFIZER,69.0,YR,F,Y,72.0,...,"20527.0, 20527.0, nan, nan, nan","nan, nan, 60.0, 60.0, nan","nan, nan, MG, MG, nan","Tablet, Tablet, nan, nan, nan","nan, nan, nan, QD, nan","Hot flush, Feeling abnormal, Abdominal pain up...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",NaN,NaN,"Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [22]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'age_cod', 'sex', 'e_sub', 'wt', 'wt_cod', 'rept_dt', 'occp_cod',
       'occr_country', 'role_cod_drug', 'drugname_drug', 'prod_ai_drug',
       'val_vbm_drug', 'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'dur_cod_ther',
       'outc_cod_outc', 'indi_pt_indi'],
      dtype='object')